default_platform(:ios)

platform :ios do
  before_all do
    codepush_login # Make sure you've set APP_CENTER_LOGIN_TOKEN environment variable
    # OR codepush_login(login_token: "foo")
  end

  lane :deploy_to_codepush do
    codepush_release_react(
      app_name: "pharekar/MyAwesomeApp", 
      disable_duplicate_release_error: true
    )
  end

  lane :promote_to_production do
    codepush_promote(
      app_name: "pharekar/MyAwesomeApp",
      source_deployment_name: "Staging",
      destination_deployment_name: "Production",
    )
  end

  after_all do
    codepush_logout
  end
end
